### PR TITLE
Remove celebration card from India homepage

### PR DESCRIPTION
**Pull request by jamiecarter7**
This PR removes all images and html and css from the simple server.

This was a celebration card used for 20 lakh patients in India.

### CODE REVIEW

**Review by prabhanshuguptagit — APPROVED** [review]
Looks good. There's a`.DS_Store` file that got committed. Not sure why, maybe you have have a global `.gitignore` that's screwing it up?

**Comment by jamiecarter7** [comment]
I will remove that file.

**Comment by jamiecarter7** [comment]
@prabhanshuguptagit, I have removed DS_store file now.

**Comment by prabhanshuguptagit** [comment]
:shipit:

**Pull request merged**
