### PR TITLE
Fix ethiopia translations

### PR DESCRIPTION
**Pull request by prabhanshuguptagit**
**Story card:** https://www.pivotaltracker.com/story/show/171857842

## Because

Since our locale names didn't match transifex's locale names, the changes from transifex were not merged in properly.

## This addresses

- Fix Ethiopian locale names:
  `ti` -> `ti_ET`
  `om` -> `om_ET`

- Adds a `language_mapping` to transifex settings so PRs are raised with the right file names in the future:
```
settings:
  language_mapping:
    pa: pa_Guru_IN
    mr: mr_IN
    om: om_ET
    ti: ti_ET
```
- Add Amharic to available locales
- Remove unused placeholder files

### CODE REVIEW

**Comment by harimohanraj89** [comment]
Why adjust our locale keys instead of transifex's locale keys? Which one is correct?

**Comment by prabhanshuguptagit** [comment]
> Which one is correct?

After some digging ([slack](https://simpledotorg.slack.com/archives/CFK2PHJ1L/p1590488755005500)), found that the android transifex settings have this to map transifex locale names:

```
settings:
  language_mapping:
    hi_IN: hi-rIN
    bn_IN: bn-rIN
    bn_BD: bn-rBD
    pa: pa-rIN
    ta_IN: ta-rIN
    te_IN: te-rIN
    kn_IN: kn-rIN
    mr: mr-rIN
    om: om-rET
    ti: ti-rET
    am_ET: am-rET
```

We should be using `ti-ET` and `om-ET` since the app expects those locales to be supported (thanks to this transifex-fu ^). I'll add a similar mapping on `simple-server` transifex so that PRs in the future are raised with the correct file names.

**Comment by prabhanshuguptagit** [comment]
Updated the description.

**Comment by harimohanraj89** [comment]
Ah I get it. This is why the translation files had the "wrong" top-level key in that round of Ethiopia translations. Neat!

**Comment by prabhanshuguptagit** [comment]
@harimohanraj89 @kitallis What would be a good place to document the transifex settings? The android folks have got it [on docs.simple](https://docs.simple.org/engineering/localization/android#language-mappings).

**Comment by harimohanraj89** [comment]
@prabhanshuguptagit A similar page called "Server" on docs.simple.org seems good. If you're all set up with access to add pages to docs.simple, have at it 👍

**Comment by prabhanshuguptagit** [comment]
Tested on sandbox. @harimohanraj89 Could you 👀 and ✅ the docs PR as well? Thx https://github.com/simpledotorg/docs/pull/3

**Comment by harimohanraj89** [comment]
Done 👍

**Pull request merged**
