### PR TITLE
Make email query methods private

### PR DESCRIPTION
**Pull request by arku**
It doesn't make a lot of sense to leave `admin_emails`, `supervisor_emails` and similar query methods `public`. This PR makes those methods `private`.

And, replaces hash rocket syntax with ruby 1.9 hash syntax.

### CODE REVIEW

**Comment by govindkrjoshi** [comment]
Hi Arku,

Thanks for the PR. This branch has gone out of date with master. Can you please updated it?
I've marked the PR as approved, and we can merge it once it's updated. 

Thank you,
Govind.

**Comment by timcheadle** [comment]
Hey @arku, mind merging your branch with master and pushing? I'd love to merge this.

**Comment by arku** [comment]
@govindkrjoshi @timcheadle Sorry for the delay guys, missed the earlier notification.

I have updated my PR, should be good to go :rocket:

**Comment by timcheadle** [comment]
Thanks @arku!

**Pull request merged**
