### PR TITLE
Update puma to 4.3.6

### PR DESCRIPTION
**Pull request by ogirginc**
## Because

There was a bug on Puma version 4.3.5, causing it to fail when trying to
compile. It was fixed with [#2304].

## This addresses

This commit updates Gemfile.lock and removes the now redundant
explanations on readme.

[#2304]: https://github.com/puma/puma/issues/2304

### CODE REVIEW

**Comment by kitallis** [comment]
Hi @ogirginc, thanks a ton for the submission! We'll try and find sometime this week to check if nothing breaks because of the `puma` upgrade, but overall, seems like it's going to cut down a bunch of noise from the setup procedures.

Heads-up, the team is on a break in the last week of November, so if we don't get a chance to try this, we might only get to it by the first week of December.

Cheers!

**Comment by ogirginc** [comment]
Hi @kitallis. Thanks for the heads up and no worries at all!

Technically, it should not break anything according to the [changelog](https://github.com/puma/puma/blob/master/History.md#436--2020-09-05), which has only [2 bug fixes](https://github.com/puma/puma/compare/v4.3.5...4.3.6):

- Explicitly include ctype.h to fix compilation warning and build error on macOS with Xcode 12 ([#2304](https://github.com/puma/puma/issues/2304))
- Don't require json at boot ([#2269](https://github.com/puma/puma/pull/2269))

Have a nice & safe break!

**Comment by rsanheim** [comment]
I just hit the puma issue again while bootstrapping a new M1 mac, so I'm going to take a look at merging this...

**Review by rsanheim — APPROVED** [review]
Looks good @ogirginc  ! Thanks for the contribution.

**Comment by rsanheim** [comment]
side note: I had to temporarily disable some statue check requirements, as I don't believe our workflows run Standardrb checks or the "CI push" check from forked contributions.

**Comment by ogirginc** [comment]
>the "CI push" check from forked contributions.

When I pushed https://github.com/simpledotorg/simple-server/pull/1532, it did actually worked. However, Github showed me "This branch is out-of-date with the base branch" warning and I pressed the "Update Branch" button which created a merge commit. To prevent merge commit, I have pulled master, rebased and pushed but this time CI did not run. 🤷 Just thought, I should share as it might help somehow.

**Pull request merged**
