### PR TITLE
Start upgrade process to Ruby 2.6.6

### PR DESCRIPTION
**Pull request by rsanheim**
[ch2255](https://app.clubhouse.io/simpledotorg/story/2255/upgrade-ruby-to-2-6-latest)

We are currently on 2.5.1, which quite a few levels behind the latest stable release versions.

2.6.6 is the most recent in the 2.6 branch, which from what I can tell hasn't introduced any sort of language level breaking changes from 2.5.x.  Ruby 2.7.x _does_ have some significant changes, so we probably want to tackle that separately - decent summary on that here: https://prathamesh.tech/2019/12/25/all-you-need-to-know-about-ruby-2-7/

This will need https://github.com/simpledotorg/deployment/pull/300 at a minimum deployed to sandbox to verify things on actual environments.

### CODE REVIEW

**Comment by rsanheim** [comment]
CI is green, so that is a good start.

**Comment by kitallis** [comment]
Damn, ruby 2.7 looks fairly cool, wish we could go there.

**Comment by kitallis** [comment]
Earlier this year, I had discovered an [undocumented](https://simpledotorg.slack.com/archives/CFHMC60P5/p1583848641024700) (at least not clearly?) breaking change from ruby `2.5.1` to `2.6.5`,

```
[3] pry(main)> RUBY_VERSION
=> "2.5.1"

[4] pry(main)> [1, 2].to_h
TypeError: wrong element type Integer at 0 (expected array)
from (pry):4:in `to_h'

[5] pry(main)> [1, 2].to_h { |x| [x, 1] }

TypeError: wrong element type Integer at 0 (expected array)
from (pry):5:in `to_h'
```

versus

```
irb(main):001:0> RUBY_VERSION
=> "2.6.3"

irb(main):002:0> [1, 2].to_h
TypeError (wrong element type Integer at 0 (expected array))

irb(main):003:0> [1, 2].to_h { |x| [x, 1] }
=> {1=>1, 2=>1}
```

Basically the block form of `to_h` expected you to prepare a list of tuples and wouldn't work on a single element, but now it does. I don't think we use this anywhere, but just something to keep in mind.

**Review by harimohanraj89 — APPROVED** [review]
Looks good to me. Let's test this thing.

**Review by kitallis — APPROVED** [review]

**Comment by rsanheim** [comment]
> Is there a super precise log of what all has changed? Even syntactically or in subtle behavioural ways? Just so I'm not paranoid if there's other things like these that got snuck in.

Here is a changelog - its pretty massive though: https://github.com/ruby/ruby/compare/v2_5_1...v2_6_6

Here is handy little presentation with more references at the end: https://talks.gettalong.org/2018-08-viennarb/talk.html#/9

**Comment by rsanheim** [comment]
Here are some actual notes on the update from the ruby team: https://github.com/ruby/ruby/blob/v2_6_0_preview2/NEWS

**Comment by rsanheim** [comment]
[ch2255](https://app.clubhouse.io/simpledotorg/story/2255/upgrade-ruby-to-2-6-latest)

**Pull request merged**
