### PR TITLE
Progress tab: Update box shadows and add additional colours

### PR DESCRIPTION
**Pull request by jamiecarter7**
Story: None

# Because

It is not clear that the reports are clickable buttons
 
# This addresses

Not so clear UX interaction

localhost_3000_reports_progress_chc-anantpur

# Test instructions

Go to any lowest level facility report > progress tab

home-finanl-newcolour

### CODE REVIEW

**Comment by dburka** [comment]
Can you please include a screenshot?

**Comment by prabhanshuguptagit** [comment]
@jamiecarter7 Could you also include the name of the feature in the PR title? For example I might call this PR `Progress tab: Update box shadows and add additional colours`

**Review by PriyangaPKini — APPROVED** [review]
Looks good! 

[suggestion] We follow this [PR template](https://github.com/simpledotorg/simple-server/blob/master/PULL_REQUEST_TEMPLATE.md) while raising a PR. It's helpful as it gives some context to the reviewer.

**Review by dburka — CHANGES_REQUESTED** [review]
As we discussed on Slack:

- [ ] Let's be careful adding too many similar-sounding color names to the Dashboard. We now have Lavender, Purple, and Indigo. This ain't great.
- [x] We should not commit very much // commented-out code.

**Review by dburka — APPROVED** [review]
Looking clean. Nice fixes @jamiecarter7

**Pull request merged**
