### PR TITLE
District reports list view

### PR DESCRIPTION
**Pull request by claudiovallejo**
## This addresses

* Using `application` layout for `/dashboard/districts` views
* `districts/index.html.erb` is now using Bootstrap styling

### CODE REVIEW

**Comment by claudiovallejo** [comment]
@rsanheim should I remove Tailwind in this PR?

**Comment by rsanheim** [comment]
> @rsanheim should I remove Tailwind in this PR?

Sure, feel free to remove it whenever the views are converted to bootstrap.

**Comment by claudiovallejo** [comment]
@rsanheim 2 questions:
* Why are all commits from past PR appearing here if I've merged with master?
* I had no merge conflicts for `application_helper.rb`, but still seeing changes that I didn't make in this PR. How can I fix this?

**Comment by rsanheim** [comment]
> 2 questions:
> 
>     * Why are all commits from past PR appearing here if I've merged with master?

I believe that is because we are using "squash and merge" as our github merge strategy.  The diff will be useful, but the commit list will not. This [blog post](https://github.blog/2016-04-01-squash-your-commits/) may explain more.
 
>     * I had no merge conflicts for `application_helper.rb`, but still seeing changes that I didn't make in this PR. How can I fix this?

Hm, merging master into this branch should fix that I think.

**Comment by rsanheim** [comment]
Closing this PR, see #1103 instead.

**Pull request closed without merging**
