### PR TITLE
Dashboard: Recent updates card AUG update

### PR DESCRIPTION
**Pull request by jamiecarter7**
**Story card:** None

## Because

Update to 'Recent update' card on the homepage of the dashboard.

http://localhost:3000/my_facilities

## This addresses

New announcements for Simple org

## Test instructions

URL: http://localhost:3000/my_facilities
Screenshot: 

Screenshot 2022-09-21 at 18 20 31

### CODE REVIEW

**Comment by jamiecarter7** [comment]
What are ANM workers?

Should this ASHA/ANM paragraph be *India only*

**Comment by jamiecarter7** [comment]
Was this a September release? or is August correct

**Comment by dburka** [comment]
> 

This is India-only. ASHA (accredited social health activists) and ANMs (auxiliary nurse midwives) are community health workers in India. The downloadable line lists in Simple are only available in India.

**Comment by dburka** [comment]
> Was this a September release? or is August correct

Let's call this Sept

**Comment by dburka** [comment]
Once you make these changes in the comments this looks good to go. Nice work.

**Review by dburka — APPROVED** [review]

**Pull request merged**
