### PR TITLE
Use the new cohort_patients key instead of registered

### PR DESCRIPTION
**Pull request by harimohanraj89**
**Story card:** [ch1600](https://app.clubhouse.io/simpledotorg/story/1600/fix-patients-column-in-cohort-downloads)

## Because

Some downloads were trying to use an older version of the cohort query results

## This addresses

Updating download touchpoints to use the correct cohort query results:
* Monthly cohort reports
* Quarterly cohort reports
* Whatsapp graphics (web and downloadable)

These touchpoints are using the `CohortAnalyticsQuery`. I think we should decommission that thing in favor of the `CohortService`. What do you think?

### CODE REVIEW

**Review by kitallis — APPROVED** [review]
ugh

no tests broke because of this change?

**Comment by harimohanraj89** [comment]
Yuuuuup. I'm torn whether to introduce tests for this that will break, or wait until we replace this with the `CohortService`. What do you think?

**Comment by harimohanraj89** [comment]
I'm gonna ship as-is, to fix the downloads asap.

**Comment by kitallis** [comment]
That sounds good, was just going to respond 👍

**Pull request merged**
