### PR TITLE
Fix state name in FacilitySeeder

### PR DESCRIPTION
**Pull request by prabhanshuguptagit**
**Story card:** -

## Because

The `FacilitySeeder` creates facilities with state names like ` #<Region:0x00007fb2c8ea8af8>`.

## This addresses

Fix state names.

### CODE REVIEW

**Review by harimohanraj89 — APPROVED** [review]

**Comment by rsanheim** [comment]
These facilities already have proper state Regions attached to them via what the seed process does.

Does this mean the text field on Facility needs to be in sync w/ the Region model? If so, we should just remove it as soon as possible....its legacy and another way for things to fall out of sync.

**Comment by prabhanshuguptagit** [comment]
The regions are properly associated yeah, this field doesn't _have_ to be in sync for correctness. Just something I noticed in data I generated locally.

Thinking of it, I think we can start removing it right away now that `regions_prep` is done everywhere.

**Comment by rsanheim** [comment]
I pushed up a fix to make sure we are using the state names Daniel sent over, as well as some more assertions here.

**Comment by rsanheim** [comment]
> Thinking of it, I think we can start removing it right away now that `regions_prep` is done everywhere.

Yeah, we should definitely do that, as its pretty confusing right now to have a text field that doesn't really match the actual region.

**Pull request merged**
