### PR TITLE
My Facilities: Comma-formatted numbers

### PR DESCRIPTION
**Pull request by claudiovallejo**
**Story card:** [ch1827](https://app.clubhouse.io/simpledotorg/story/1827/my-facilities-comma-separated-numbers)

## Because

We should display numbers in a consistent format across the Dashboard. This PR comma-separates all numbers in "My Facilities" sections.

_Example: `1234` is now shown as `1,234`_

## This addresses

Displays comma-formatted numbers in the following Dashboard sections

1. My Facilities "Overview"
2. My Facilities "Ranked Facilities"
3. My Facilities "BP control"
4. My Facilities "Missed visits"
5. My Facilities "Registrations"

### CODE REVIEW

**Review by harimohanraj89 — APPROVED** [review]
Looks great. Hit us up if you need help setting up large enough test data to test these changes.

**Comment by claudiovallejo** [comment]
> Looks great. Hit us up if you need help setting up large enough test data to test these changes.

Thanks @harimohanraj89 that would be great. Local data is not large enough to test, so I manually entered numbers to make sure they worked. How easy is it to setup large test data?

**Comment by harimohanraj89** [comment]
@claudiovallejo if you've hardcoded numbers in all the touchpoints to test, that should suffice #clever

Generating large datasets will probably take some time, and won't get us much better testing info :smile:

**Comment by claudiovallejo** [comment]
@kitallis this PR wasn't ready to merge yet. Daniel gave feedback to show dashes instead of zeros in tables. I'll open a new PR to implement Daniel's feedback.

**Pull request merged**
