### PR TITLE
Grab data even if a facility _just_ has follow ups

### PR DESCRIPTION
**Pull request by rsanheim**
...and no registered or assigned patients

**Story card:** [sc-6496](https://app.shortcut.com/simpledotorg/story/6496/follow-up-data-not-visible-in-district-details-but-visible-in-facility-details)

Fix issue where a facility has no registered or assigned patients, but does have follow up numbers.

### CODE REVIEW

**Review by vkrmis — COMMENTED** [review]
@rsanheim we also skip facilities with no patients in the view (non_facility_details)

**Comment by rsanheim** [comment]
> @rsanheim we also skip facilities with no patients in the view (non_facility_details)


Fixed the query underlying that.

I'm not sure we need that skip at all in the view - maybe it was there to prevent a huge list of empty data when a Region is just getting setup? I could go either way on removing it.

**Review by vkrmis — COMMENTED** [review]
lgtm

**Comment by vkrmis** [comment]
> maybe it was there to prevent a huge list of empty data

That's probably it

**Pull request merged**
