### PR TITLE
More Region backfill fixes

### PR DESCRIPTION
**Pull request by prabhanshuguptagit**
**Story card:** [ch1455](https://app.clubhouse.io/simpledotorg/story/1455/create-region-schema-run-dry-run-of-region-backfill-in-prod)

## This addresses

Fixes some bugs in Region backfill script.

### CODE REVIEW

**Review by rsanheim — APPROVED** [review]
I think it makes sense - can you say more for when this is needed?

**Comment by prabhanshuguptagit** [comment]
@rsanheim There's a bunch of discussion threads open in https://github.com/simpledotorg/simple-server/pull/1486, let's address them all in this PR.

**Comment by prabhanshuguptagit** [comment]
> I think it makes sense - can you say more for when this is needed?

This breaks when creating the root region (with a `NullRegion` as parent) from the backfill.

**Review by kitallis — APPROVED** [review]
lgtm

**Pull request merged**
