### PR TITLE
Added rake task for anonymizing audit logs

### PR DESCRIPTION
**Pull request by timmyjose**
This is as part of https://www.pivotaltracker.com/n/projects/2184102/stories/164201136 to fix existing data which has appointments (created via Card Reader) incorrectly marked as "scheduled" instead of "visited".

### CODE REVIEW

**Comment by divs1210** [comment]
Why are we doing this?

**Comment by timmyjose** [comment]
> Why are we doing this?

I have updated the description of the PR. This is as part of fixing the existing incorrectly marked Card Reader appointments. This task will anonymize the audit logs from production so that they can be used on the sandbox for testing the script that will update suitable appointments from "scheduled" to "visited".

The WIP part is that since we have a huge number of audit logs, we need to filter out the audit logs of type "fetch" since we are only interested in audit logs of type "create" and "update" as part of the clean-up process.

**Comment by govindkrjoshi** [comment]
We want to test the rake task to update overdue cardreader appointments on sandbox before running it on production.

**Comment by timmyjose** [comment]
The approach we have decided on is to use `skip` as provided by the `data-anonymization` gem to filter out the appointments of interest (action type `create` and `update`).

**Comment by divs1210** [comment]
@govind We should probably rename the `:full_database` task at some point, or put everything under it, as our sandbox environment should have Users and AuditLogs to be fully testable.

**Pull request merged**
